# Generated by Django 4.2.11 on 2024-04-04 13:36

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default=1,
                max_length=100,
                verbose_name=django.contrib.auth.models.User,
            ),
            preserve_default=False,
        ),
    ]
