# Generated by Django 4.2.11 on 2024-04-04 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_task_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="status",
            new_name="status1",
        ),
    ]
